source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/bitmovin/cocoapod-specs.git'

pod 'BitmovinPlayer', '~>3.1.0'

target 'BitmovinAnalyticsCollector-Example-BitmovinPlayerV3-iOS' do
    use_frameworks!
    platform :ios, '12.0'
    pod 'BitmovinAnalyticsCollector/Core', :path => '../BitmovinAnalyticsCollector.v2.podspec'
    pod 'BitmovinAnalyticsCollector/AVPlayer', :path => '../BitmovinAnalyticsCollector.v2.podspec'
    pod 'BitmovinAnalyticsCollector/BitmovinPlayer', :path => '../BitmovinAnalyticsCollector.v2.podspec'
    pod 'GoogleAds-IMA-iOS-SDK', '3.12.1'
    pod 'google-cast-sdk', '4.6.1'
end

target 'BitmovinAnalyticsCollector-Example-BitmovinPlayerV3-tvOS' do
    use_frameworks!
    platform :tvos, '12.0'
    pod 'BitmovinAnalyticsCollector/Core', :path => '../BitmovinAnalyticsCollector.v2.podspec'
    pod 'BitmovinAnalyticsCollector/AVPlayer', :path => '../BitmovinAnalyticsCollector.v2.podspec'
    pod 'BitmovinAnalyticsCollector/BitmovinPlayer', :path => '../BitmovinAnalyticsCollector.v2.podspec'
end

target 'BitmovinAnalyticsCollector-Tests-BitmovinPlayerV3-iOS' do
    use_frameworks!
    platform :ios, '12.0'
    pod 'BitmovinAnalyticsCollector/Core', :path => '../BitmovinAnalyticsCollector.v2.podspec', :testspecs => ['CoreTests']
    pod 'BitmovinAnalyticsCollector/AVPlayer', :path => '../BitmovinAnalyticsCollector.v2.podspec', :testspecs => ['AVPlayerTests']
    pod 'BitmovinAnalyticsCollector/BitmovinPlayer', :path => '../BitmovinAnalyticsCollector.v2.podspec', :testspecs => ['BitmovinPlayerTests']
end
