source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/bitmovin/cocoapod-specs.git'

pod 'BitmovinPlayer', '~>3.0.0-rc.6'

target 'BitmovinAnalyticsCollector-Example-BitmovinPlayerV3-iOS' do
    use_frameworks!
    platform :ios, '12.0'
    pod 'BitmovinAnalyticsCollector/CoreTarget12', :path => '../'
    pod 'BitmovinAnalyticsCollector/BitmovinPlayerV3', :path => '../'
    pod 'GoogleAds-IMA-iOS-SDK', '3.12.1'
end

target 'BitmovinAnalyticsCollector-Example-BitmovinPlayerV3-tvOS' do
    use_frameworks!
    platform :tvos, '12.0'
    pod 'BitmovinAnalyticsCollector/CoreTarget12', :path => '../'
    pod 'BitmovinAnalyticsCollector/BitmovinPlayerV3', :path => '../'
end

target 'BitmovinAnalyticsCollector-Tests-BitmovinPlayerV3-iOS' do
    use_frameworks!
    platform :ios, '12.0'
    pod 'BitmovinAnalyticsCollector/CoreTarget12', :path => '../', :testspecs => ['CoreTarget12Tests']
    pod 'BitmovinAnalyticsCollector/BitmovinPlayerV3', :path => '../', :testspecs => ['BitmovinPlayerV3Tests']
end