source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/bitmovin/cocoapod-specs.git'

pod 'BitmovinPlayer', '2.51.0'

target 'BitmovinAnalyticsCollector-Example-BitmovinPlayerV3-iOS' do
    use_frameworks!
    platform :ios, '9.0'
    pod 'BitmovinAnalyticsCollector/Core', :path => '../'
    pod 'BitmovinAnalyticsCollector/BitmovinPlayerV3', :path => '../'
    pod 'GoogleAds-IMA-iOS-SDK', '3.11.1'
end

target 'BitmovinAnalyticsCollector-Example-BitmovinPlayerV3-tvOS' do
    use_frameworks!
    platform :tvos
    pod 'BitmovinAnalyticsCollector/Core', :path => '../'
    pod 'BitmovinAnalyticsCollector/BitmovinPlayerV3', :path => '../'
end

target 'BitmovinAnalyticsCollector-Tests-BitmovinPlayerV3-iOS' do
    use_frameworks!
    platform :ios, '9.0'
    pod 'BitmovinAnalyticsCollector/Core', :path => '../', :testspecs => ['CoreTests']
    pod 'BitmovinAnalyticsCollector/BitmovinPlayerV3', :path => '../', :testspecs => ['BitmovinPlayerV3Tests']
end