
target 'BitmovinAnalyticsCollector_Example' do
    use_frameworks!
    platform :ios, '9.0'
    pod 'BitmovinAnalyticsCollector', :path => '../'
    source 'https://github.com/bitmovin/cocoapod-specs.git'
    pod 'BitmovinPlayer', '2.51.0'
    pod 'GoogleAds-IMA-iOS-SDK', '3.9.2'
end

target 'BitmovinAnalyticsCollector_tvOSExample' do
    pod 'BitmovinAnalyticsCollector', :path => '../'
    use_frameworks!
    platform :tvos
    source 'https://github.com/bitmovin/cocoapod-specs.git'
    pod 'BitmovinPlayer', '2.51.0'

end
