platform :ios, '9.0'
use_frameworks!

target 'BitmovinAnalyticsCollector_Example' do
  pod 'BitmovinAnalyticsCollector', :path => '../'
  pod 'BitmovinPlayer', git: 'https://github.com/bitmovin/bitmovin-player-ios-sdk-cocoapod.git', tag: '2.7.0'
end
