use_frameworks!

target 'BitmovinAnalyticsCollector_Example' do
  pod 'BitmovinAnalyticsCollector', :path => '../'

  target 'BitmovinAnalyticsCollector_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
