# Taken from https://medium.com/@hamdullahshah/generating-code-from-xcode-configurations-6fd203ec69ef
# Usage:
# (./BuildConfig.sh "VERSION=$VERSION\nSECONDVAR=asf") > BitmovinAnalyticsCollector/Classes/Collector/util/BuildConfig.swift
echo "//Generated file please do not edit"
printf "//\n//\n//generated by BuildConfig.sh\n"
printf "import Foundation\n\n"
echo "struct BuildConfig { "
echo "  fileprivate init() {}"
echo "$1" |\
sed "s/^/    static let /" |\
sed -E 's/=(.*)/ = "\1"/'
echo "}"