name: Select Xcode based on version
description: Finds and selects Xcode for the action run based on version
inputs:
  version:
    description: Xcode version to select, e.g. '14' or '14.1'
    required: true
runs:
  using: "composite"
  steps:
    - name: Find and Select Xcode by version
      run: |
        XCODE_APPLICATION_NAME="$(ls /Applications | sort -r | grep -iF -m 1 Xcode-${{ inputs.version }})"
        if [ -z "$XCODE_APPLICATION_NAME" ]; then
          echo "Unable to find Xcode with version '${{ inputs.version }}'" >&2
          exit 1
        fi

        XCODE_PATH="/Applications/${XCODE_APPLICATION_NAME}"
        echo "Found Xcode for version '${{ inputs.version }}' at: ${XCODE_PATH}"
        echo "DEVELOPER_DIR=${XCODE_PATH}/Contents/Developer" >> $GITHUB_ENV
      shell: bash
