source 'https://github.com/bitmovin/cocoapod-specs.git'
source 'https://cdn.cocoapods.org/'

def for_ios 
  platform :ios, '12.0'
end

def for_tvos 
  platform :tvos, '12.0'
end

def bitmovin_player
  pod 'BitmovinPlayer', '~>3.1.0'
end

def amazon_ivs_player
  pod 'AmazonIVSPlayer', '~> 1.16.0'
end

def bitmovin_collector
  pod 'BitmovinAnalyticsCollector/Core', :path => '../BitmovinAnalyticsCollector.v2.podspec'
  pod 'BitmovinAnalyticsCollector/AVPlayer', :path => '../BitmovinAnalyticsCollector.v2.podspec'
  pod 'BitmovinAnalyticsCollector/BitmovinPlayer', :path => '../BitmovinAnalyticsCollector.v2.podspec'
end

def bitmovin_collector_tests 
  pod 'BitmovinAnalyticsCollector/Core', :path => '../BitmovinAnalyticsCollector.v2.podspec', :testspecs => ['CoreTests']
  pod 'BitmovinAnalyticsCollector/AVPlayer', :path => '../BitmovinAnalyticsCollector.v2.podspec', :testspecs => ['AVPlayerTests'] 
  pod 'BitmovinAnalyticsCollector/BitmovinPlayer', :path => '../BitmovinAnalyticsCollector.v2.podspec', :testspecs => ['BitmovinPlayerTests']
end

def google_Adsima_sdk
  pod 'GoogleAds-IMA-iOS-SDK', '3.12.1'
end

def google_cast_sdk
  pod 'google-cast-sdk', '4.6.1'
end


target 'CollectorDemoApp' do
  use_frameworks!
  for_ios
  
  bitmovin_player
  amazon_ivs_player

  bitmovin_collector
  bitmovin_collector_tests
  
  google_Adsima_sdk
  google_cast_sdk
end

target 'CollectorDemoAppTV' do
  use_frameworks!
  for_tvos
  bitmovin_player
  bitmovin_collector
  bitmovin_collector_tests
end
