source 'https://github.com/bitmovin/cocoapod-specs.git'
source 'https://cdn.cocoapods.org/'

def for_ios 
  platform :ios, '12.0'
end

def for_tvos 
  platform :tvos, '12.0'
end

def bitmovin_player
  pod 'BitmovinPlayer', '~> 3.35.0'
end

def amazon_ivs_player
  pod 'AmazonIVSPlayer', '~> 1.17.0'
end

def collectors
  pod 'BitmovinAnalyticsCollector/Core', :path => '../BitmovinAnalyticsCollector.v2.podspec'
  pod 'BitmovinAnalyticsCollector/AVPlayer', :path => '../BitmovinAnalyticsCollector.v2.podspec'
  pod 'BitmovinAnalyticsCollector/BitmovinPlayer', :path => '../BitmovinAnalyticsCollector.v2.podspec'
  pod 'BitmovinAnalyticsCollector/AmazonIVSPlayer', :path => '../BitmovinAnalyticsCollector.v2.podspec'
end


def google_Adsima_sdk
  pod 'GoogleAds-IMA-iOS-SDK', '3.18.4'
end

def google_cast_sdk
  pod 'google-cast-sdk', '4.6.1'
end


target 'CollectorDemoApp' do
  use_frameworks!
  for_ios
  google_Adsima_sdk
  google_cast_sdk
end

target 'CollectorDemoAppCocoa' do
  use_frameworks!
  for_ios
  collectors
  google_Adsima_sdk
  google_cast_sdk
end

target 'CollectorDemoAppTV' do
  use_frameworks!
  for_tvos
end
