name: Build workspace
on:
  push:
    paths:
      - '**/*.swift'
      - '**/*.h'
      - '**/*.hh'
      - '**/*.m'
      - '**/*.mm'
      - '**/*.plist'
      - '**/*.xcfilelist'
      - '**/*.xcconfig'
      - '**/*.xcscheme'
      - '**/*.pbxproj'
      - 'Podfile*'
      - 'Gemfile*'
      - 'fastlane/**'
      - 'Brewfile*'
      - 'CollectorDemoApp/Podfile'
      - 'CollectorDemoApp/Podfile.lock'
      - '.github/actions/**'
      - '.github/workflows/build_collector_app.yml'
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_call:
    inputs:
      ref:
        description: GitHub ref (branch or tag) to check out
        type: string
        required: true
env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
jobs:
  build_apps:
    name: "Build Collector Demo Apps"
    runs-on: self-hosted
    concurrency:
      group: build-workspace-apps-${{ inputs.ref || github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: ./.github/actions/select-xcode
        with:
          version: 14
      - uses: ./.github/actions/prepare-dependencies
      - name: Build Collector demo app iOS
        run: bundle exec fastlane build_debug_app
      - name: Build Collector demo app tvOS
        run: bundle exec fastlane build_tvos_debug_app
