name: Test workspace
on:
  push:
    paths:
      - '**/*.swift'
      - '**/*.h'
      - '**/*.hh'
      - '**/*.m'
      - '**/*.mm'
      - '**/*.plist'
      - '**/*.xcfilelist'
      - '**/*.xcconfig'
      - '**/*.xcscheme'
      - '**/*.pbxproj'
      - 'Gemfile*'
      - 'fastlane/**'
      - '.github/actions/**'
      - '.github/workflows/test_collector.yml'
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_call:
    inputs:
      ref:
        description: GitHub ref (branch or tag) to check out
        type: string
        required: true
env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
jobs:
  test_package:
    name: "Test SPM Package"
    runs-on: self-hosted
    concurrency:
      group: build-workspace-apps-${{ inputs.ref || github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: ./.github/actions/select-xcode
        with:
          version: 14
      - uses: ./.github/actions/prepare-dependencies
      - uses: ./.github/actions/generate-mocks
      - name: Test Collector spm package
        run: bundle exec fastlane test_collector
    